version: '3.8'
services:
  alifelived-backend:
    container_name: alifelived-backend
    restart: 'no'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '9229:9229'
    links:
      - redis
    command: npm run-script test:e2e # use this to run / debug tests
    # volumes needed for debugging but not for running tests since code is not changing
    # volumes:
    # - ~/aLifeLivedBackend:/app # set the first part of this to your local source folder
  redis:
    container_name: all-redis
    image: 'redis:5'
